name: TelecomInfo
version: '${project.version}'
main: me.kardoskevin07.telecominfo.TelecomInfo
api-version: 1.17
author: 008kevin
depend: [Telecom]
softdepend: [PlaceholderAPI]
commands:
  listCarriers:
    description: Your description
    usage: /<command> [page number]
    permission: yourplugin.yourcommandpermission
  carrierInfo:
    description: Your description
    usage: /<command> [subcommand] [carrier name]
    permission: yourplugin.yourcommandpermission