name: TelecomInfo
version: '${project.version}'
main: me.kardoskevin07.telecominfo.TelecomInfo
api-version: 1.19
author: 008kevin
depend: [Telecom]
commands:
  listCarriers:
    description: Your description
    usage: /<command>
    permission: yourplugin.yourcommandpermission